# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for 信息汇总桌面工具 backend."""

import sys
import os

# Increase recursion limit for large dependency trees
sys.setrecursionlimit(5000)

# Paths
project_root = os.path.dirname(os.path.abspath(SPECPATH))

# Model data directory (may not exist if model not downloaded yet)
model_dir = os.path.join(project_root, "models", "paraphrase-multilingual-MiniLM-L12-v2")
model_datas = []
if os.path.isdir(model_dir):
    model_datas.append((model_dir, "models/paraphrase-multilingual-MiniLM-L12-v2"))

block_cipher = None

a = Analysis(
    ["run_backend.py"],
    pathex=[project_root],
    binaries=[],
    datas=[
        (".env.template", "."),
    ] + model_datas,
    hiddenimports=[
        # chromadb internals
        "chromadb",
        "chromadb.api",
        "chromadb.api.client",
        "chromadb.api.async_client",
        "chromadb.api.async_api",
        "chromadb.api.segment",
        "chromadb.api.types",
        "chromadb.auth",
        "chromadb.auth.token",
        "chromadb.auth.token_authn",
        "chromadb.config",
        "chromadb.db",
        "chromadb.db.base",
        "chromadb.db.impl",
        "chromadb.db.impl.sqlite",
        "chromadb.db.mixins",
        "chromadb.ingest",
        "chromadb.ingest.impl",
        "chromadb.segment",
        "chromadb.segment.impl",
        "chromadb.segment.impl.vector",
        "chromadb.segment.impl.vector.local_persistent_hnsw",
        "chromadb.segment.impl.metadata",
        "chromadb.segment.impl.metadata.sqlite",
        "chromadb.telemetry",
        "chromadb.telemetry.product",
        "chromadb.telemetry.product.events",
        "chromadb.types",
        "chromadb.utils",
        "chromadb.utils.data_loaders",
        "chromadb.utils.embedding_functions",
        "chromadb.utils.embedding_functions.sentence_transformer_embedding_function",
        "chromadb.utils.embedding_functions.openai_embedding_function",
        "chromadb.utils.embedding_functions.onnx_mini_lm_l6_v2",

        # onnxruntime
        "onnxruntime",
        "onnxruntime.capi",
        "onnxruntime.capi.onnxruntime_pybind11_state",
        "onnxruntime.transformers",
        "onnxruntime.transformers.onnx_model",

        # sentence-transformers
        "sentence_transformers",
        "sentence_transformers.SentenceTransformer",
        "sentence_transformers.models",
        "sentence_transformers.models.Transformer",
        "sentence_transformers.models.Pooling",
        "sentence_transformers.models.Dense",
        "sentence_transformers.models.Normalize",
        "sentence_transformers.evaluation",
        "sentence_transformers.readers",
        "sentence_transformers.datasets",
        "sentence_transformers.losses",
        "sentence_transformers.cross_encoder",
        "sentence_transformers.util",

        # transformers
        "transformers",
        "transformers.models.bert",
        "transformers.models.bert.modeling_bert",
        "transformers.models.bert.tokenization_bert",
        "transformers.models.auto",
        "transformers.models.auto.modeling_auto",
        "transformers.models.auto.tokenization_auto",
        "transformers.tokenization_utils",
        "transformers.tokenization_utils_base",
        "transformers.configuration_utils",
        "transformers.modeling_utils",
        "transformers.pipelines",
        "transformers.utils",
        "transformers.utils.hub",
        "tokenizers",
        "tokenizers.decoders",
        "tokenizers.normalizers",
        "tokenizers.pre_tokenizers",
        "tokenizers.processors",
        "tokenizers.trainers",

        # torch
        "torch",
        "torch.nn",
        "torch.nn.functional",
        "torch.utils",
        "torch.utils.data",
        "torch._C",
        "torch._C._nn",
        "torch.multiprocessing",
        "multiprocessing",
        "multiprocessing.pool",
        "multiprocessing.process",

        # numpy / scipy / sklearn
        "numpy",
        "numpy.core",
        "numpy.core._dtype_ctypes",
        "numpy.core.multiarray",
        "numpy.linalg",
        "scipy",
        "scipy.sparse",
        "scipy.sparse.csgraph",
        "scipy.sparse.linalg",
        "scipy.spatial",
        "sklearn",
        "sklearn.metrics",
        "sklearn.metrics.pairwise",

        # huggingface_hub
        "huggingface_hub",
        "huggingface_hub.file_download",
        "huggingface_hub.snapshot_download",
        "huggingface_hub.hf_api",
        "huggingface_hub.utils",

        # uvicorn
        "uvicorn",
        "uvicorn.config",
        "uvicorn.server",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.httptools_impl",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.logging",

        # fastapi / starlette
        "fastapi",
        "fastapi.middleware",
        "fastapi.middleware.cors",
        "starlette",
        "starlette.middleware",
        "starlette.middleware.cors",
        "starlette.middleware.base",
        "anyio",
        "h11",
        "httpcore",

        # pydantic
        "pydantic",
        "pydantic_settings",
        "pydantic_core",
        "pydantic.deprecated",
        "pydantic.deprecated.decorator",

        # Other project deps
        "httpx",
        "bs4",
        "beautifulsoup4",
        "readability_lxml",
        "lxml",
        "lxml.etree",
        "lxml.html",
        "openai",
        "anthropic",
        "python_dotenv",
        "python_frontmatter",
        "markdown",
        "sse_starlette",
        "sse_starlette.sse",
        "yaml",
        "PIL",
        "PIL.Image",
        "tiktoken",
        "tqdm",
        "regex",
        "filelock",
        "packaging",
        "certifi",
        "idna",
        "charset_normalizer",
        "urllib3",

        # backend modules (ensure all are discovered)
        "backend",
        "backend.main",
        "backend.config",
        "backend.models",
        "backend.models.schemas",
        "backend.models.prompts",
        "backend.routes",
        "backend.routes.scan",
        "backend.routes.config",
        "backend.routes.discover",
        "backend.routes.embeddings",
        "backend.routes.obsidian",
        "backend.services",
        "backend.services.llm_client",
        "backend.services.embedding_service",
        "backend.services.content_extractor",
        "backend.services.obsidian_writer",
        "backend.services.web_search",
        "backend.services.ai_analyzer",
        # stdlib modules sometimes missed
        "asyncio",
        "concurrent.futures",
        "json",
        "logging",
        "sqlite3",
        "email",
        "email.mime",
        "email.mime.text",
        "html",
        "xml",
        "xml.etree",
        "xml.etree.ElementTree",
        "collections",
        "collections.abc",
        "dataclasses",
        "enum",
        "functools",
        "hashlib",
        "importlib",
        "importlib.metadata",
        "io",
        "itertools",
        "pathlib",
        "tempfile",
        "threading",
        "typing",
        "typing_extensions",
        "uuid",
        "zipfile",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "pandas",
        "jupyter",
        "IPython",
        "notebook",
        "spacy",
        "nltk",
        "tensorflow",
        "torchvision",
        "torchaudio",
        "torch.cuda",
        "caffe2",
        "tornado",
        "sqlalchemy",
        "alembic",
        "pytest",
        "setuptools",
        "pip",
        "wheel",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="run_backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name=os.path.join("..", "pyinstaller-dist", "run_backend"),
)
